apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: prepull
spec:
  selector:
    matchLabels:
      name: prepull
  template:
    metadata:
      labels:
        name: prepull
    spec:
      containers:
      - name: prepull
        image: gcr.io/sky-burst/skyburst:latest
        command: ["exit", "0"]