apiVersion: batch/v1
kind: Job
metadata:
  name: sleep-10
spec: 
  template: 
    spec: 
      containers: 
      - name: sleep
        image: alpine:latest
        command: ["sleep", "7.337767247338158"]
        resources: 
          limits: 
            cpu: 0.1
      restartPolicy: Never
  backoffLimit: 1