apiVersion: kubeflow.org/v1
kind: TFJob
metadata:
  name: tfjob-resnet
  namespace: kubeflow
spec:
  tfReplicaSpecs:
    Worker:
      replicas: 2
      restartPolicy: OnFailure
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          containers:
            - name: tensorflow
              image: us-west2-docker.pkg.dev/sky-burst/mnist/resnet:v1
              resources:
                limits:
                  nvidia.com/gpu: 1
              command: ["sh", "-c"]
              args: [". $(conda info --base)/etc/profile.d/conda.sh && conda activate resnet && python -u models/official/resnet/resnet_main.py --use_tpu=False --mode=train --train_batch_size=256 --train_steps=250 --iterations_per_loop=125 --data_dir=gs://cloud-tpu-test-datasets/fake_imagenet --model_dir=resnet-model-dir --amp --xla --loss_scale=128"]